sudo: false
env:
- XSLT_BUILD_DIR=$TRAVIS_BUILD_DIR/.travis/vendor
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
# Download and compile libxslt as apt-get is unavailable for container-based infrastructure
- curl http://xmlsoft.org/sources/libxslt-1.1.28.tar.gz -o /tmp/libxslt.tar.gz
- mkdir /tmp/libxslt && tar -C /tmp/libxslt -xvf /tmp/libxslt.tar.gz
- cd /tmp/libxslt/libxslt-1.1.28 && ./configure --prefix=$XSLT_BUILD_DIR && make && make install
- cd $TRAVIS_BUILD_DIR
- export PATH=$PATH:$XSLT_BUILD_DIR/bin
script:
- make install && make test && make provision
- make tidy
language: node_js
node_js:
- 0.12.2
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && make deploy
notifications:
  slack:
    secure: n+hRxiXZgLhVJbaK7QkGufO+aun7wt7yTvAN1TfMVM1cQutcm/aKX4lUYsfTDzWINPKd69Zq/iSk8HxoGxpfhxHnLNblpwdAiYdHFXIVXTe3x4VPGRSg8Q8pSi8uMcswX5qWse5Ft0Yg5YdckA+pydg7lci/KAksZ33mJPdRDkA=
